from . import bigcommerce_config
from . import bigcommerce_job
from . import bigcommerce_tax
from . import bigcommerce_channel
from . import bigcommerce_category
from . import bigcommerce_customer_group
from . import bigcommerce_price_list
from . import bigcommerce_product
from . import bigcommerce_cart
from . import bigcommerce_refund
from . import bigcommerce_webhook
from . import bigcommerce_update_log
from . import bigcommerce_order_status_history
from . import bigcommerce_dashboard
from . import bigcommerce_product_dashboard
from . import sale_order
from . import res_partner
