{
    "name": "Security Simulator",
    "summary": "Simulate user access rights, record rules, groups, and field restrictions",
    "version": "17.0.1.0.0",
    "category": "Technical",
    "author": "ModuleDex",
    "website": "https://apps.odoo.com/apps/modules/browse?author=ModuleDex",
    "support": "moduledex@gmail.com",
    "license": "LGPL-3",
    "depends": ["base"],
    "data": [
        "security/ir.model.access.csv",
        "views/mdx_security_simulator_views.xml",
    ],
    "images": [
        "static/description/banner.png",
        "static/description/screenshots/01_security_simulations_list.png",
        "static/description/screenshots/02_simulation_overview.png",
        "static/description/screenshots/03_access_rights.png",
        "static/description/screenshots/04_record_rules.png",
        "static/description/screenshots/05_user_groups.png",
        "static/description/screenshots/06_menus_actions.png",
    ],
    "installable": True,
    "application": False,
}
