"""Link the native restrictions back to the rule that generated them."""

from odoo import fields, models


class IrAccess(models.Model):
    _inherit = "ir.access"

    mdx_profile_id = fields.Many2one(
        "mdx.access.profile", string="Access Profile", ondelete="cascade", index="btree_not_null",
        readonly=True,
        help="Set when this restriction was generated by an access profile. Edit the profile, "
             "not this row: it is rewritten whenever the profile changes.")
    mdx_model_rule_id = fields.Many2one(
        "mdx.access.model.rule", string="Access Profile Rule", ondelete="cascade",
        index="btree_not_null", readonly=True)
